### ISSUE TITLE
Compose syntax is incorrect

### ISSUE THREAD

**Issue by IosifZ** [janw/pi-hole-influx#27]
While trying to setup this great peace of software I noticed that the syntax for the environment is not correct.
Maybe someone can update the description

```yaml
piholeinflux:
    image: registry.gitlab.com/janw/pi-hole-influx
    container_name: piholeinflux
    hostname: piholeinflux    
    environment:
      - PIHOLE_INFLUXDB_HOST="name of the influxdb installation (hostname or service name"
      - PIHOLE_INFLUXDB_PORT="8086"
      - PIHOLE_INFLUXDB_USERNAME="pihole"
      - PIHOLE_INFLUXDB_PASSWORD="pihole"
      - PIHOLE_INFLUXDB_DATABASE="pihole"
      - PIHOLE_INSTANCES="pihole=http://xxx.xxx.xxx.xxx/admin/api.php" #Replace the group of X with Pi-Hole's IP address
    restart: unless-stopped
```
